
spring:
  h2:
    console:
      enabled: true


  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100


  servlet:
    multipart:
      location: C:/programming/spring/aboutme_back/src/main/resources/image/

#  web:
#    resources:
#      static-locations[0]: file:src/main/resources/static/
#      static-locations[1]: classpath:/static/


  devtools:
    livereload:
      enabled: true

  freemarker:
    cache: false